// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sessions

import (
	"database/sql"
)

type MagicToken struct {
	TokenHash string         `json:"token_hash"`
	Email     string         `json:"email"`
	UserID    sql.NullString `json:"user_id"`
	ExpiresAt int64          `json:"expires_at"`
	CreatedAt int64          `json:"created_at"`
}

type OauthClient struct {
	ClientID                string         `json:"client_id"`
	ClientSecretHash        sql.NullString `json:"client_secret_hash"`
	ClientName              sql.NullString `json:"client_name"`
	RedirectUris            string         `json:"redirect_uris"`
	IsPublic                int64          `json:"is_public"`
	TokenEndpointAuthMethod sql.NullString `json:"token_endpoint_auth_method"`
	CreatedAt               int64          `json:"created_at"`
}

type OauthCode struct {
	CodeHash            string         `json:"code_hash"`
	ClientID            string         `json:"client_id"`
	UserID              string         `json:"user_id"`
	RedirectUri         string         `json:"redirect_uri"`
	Scope               sql.NullString `json:"scope"`
	Resource            sql.NullString `json:"resource"`
	CodeChallenge       string         `json:"code_challenge"`
	CodeChallengeMethod sql.NullString `json:"code_challenge_method"`
	ExpiresAt           int64          `json:"expires_at"`
	CreatedAt           int64          `json:"created_at"`
}

type OauthConsent struct {
	ID        string `json:"id"`
	UserID    string `json:"user_id"`
	ClientID  string `json:"client_id"`
	Scopes    string `json:"scopes"`
	GrantedAt int64  `json:"granted_at"`
}

type OauthToken struct {
	AccessTokenHash  string         `json:"access_token_hash"`
	RefreshTokenHash sql.NullString `json:"refresh_token_hash"`
	ClientID         string         `json:"client_id"`
	UserID           string         `json:"user_id"`
	Scope            sql.NullString `json:"scope"`
	Resource         sql.NullString `json:"resource"`
	ExpiresAt        int64          `json:"expires_at"`
	CreatedAt        int64          `json:"created_at"`
}

type Session struct {
	SessionID string `json:"session_id"`
	UserID    string `json:"user_id"`
	ExpiresAt int64  `json:"expires_at"`
	CreatedAt int64  `json:"created_at"`
}

type ShortUrl struct {
	ID        int64  `json:"id"`
	ShortID   string `json:"short_id"`
	FullPath  string `json:"full_path"`
	CreatedAt int64  `json:"created_at"`
}

type UserKey struct {
	UserID       string        `json:"user_id"`
	KekVersion   int64         `json:"kek_version"`
	EncryptedDek []byte        `json:"encrypted_dek"`
	CreatedAt    int64         `json:"created_at"`
	RotatedAt    sql.NullInt64 `json:"rotated_at"`
}
