// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: sessions_consent.sql

package sessions

import (
	"context"
)

const createConsent = `-- name: CreateConsent :one

INSERT INTO oauth_consents (id, user_id, client_id, scopes, granted_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, user_id, client_id, scopes, granted_at
`

type CreateConsentParams struct {
	ID        string `json:"id"`
	UserID    string `json:"user_id"`
	ClientID  string `json:"client_id"`
	Scopes    string `json:"scopes"`
	GrantedAt int64  `json:"granted_at"`
}

// OAuth consent queries for the shared sessions database
func (q *Queries) CreateConsent(ctx context.Context, arg CreateConsentParams) (OauthConsent, error) {
	row := q.db.QueryRowContext(ctx, createConsent,
		arg.ID,
		arg.UserID,
		arg.ClientID,
		arg.Scopes,
		arg.GrantedAt,
	)
	var i OauthConsent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClientID,
		&i.Scopes,
		&i.GrantedAt,
	)
	return i, err
}

const deleteConsent = `-- name: DeleteConsent :exec
DELETE FROM oauth_consents WHERE user_id = ? AND client_id = ?
`

type DeleteConsentParams struct {
	UserID   string `json:"user_id"`
	ClientID string `json:"client_id"`
}

func (q *Queries) DeleteConsent(ctx context.Context, arg DeleteConsentParams) error {
	_, err := q.db.ExecContext(ctx, deleteConsent, arg.UserID, arg.ClientID)
	return err
}

const getConsent = `-- name: GetConsent :one
SELECT id, user_id, client_id, scopes, granted_at
FROM oauth_consents
WHERE user_id = ? AND client_id = ?
`

type GetConsentParams struct {
	UserID   string `json:"user_id"`
	ClientID string `json:"client_id"`
}

func (q *Queries) GetConsent(ctx context.Context, arg GetConsentParams) (OauthConsent, error) {
	row := q.db.QueryRowContext(ctx, getConsent, arg.UserID, arg.ClientID)
	var i OauthConsent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClientID,
		&i.Scopes,
		&i.GrantedAt,
	)
	return i, err
}

const listConsentsForUser = `-- name: ListConsentsForUser :many
SELECT id, user_id, client_id, scopes, granted_at
FROM oauth_consents
WHERE user_id = ?
ORDER BY granted_at DESC
`

func (q *Queries) ListConsentsForUser(ctx context.Context, userID string) ([]OauthConsent, error) {
	rows, err := q.db.QueryContext(ctx, listConsentsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OauthConsent{}
	for rows.Next() {
		var i OauthConsent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ClientID,
			&i.Scopes,
			&i.GrantedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConsentScopes = `-- name: UpdateConsentScopes :one
UPDATE oauth_consents
SET scopes = ?, granted_at = ?
WHERE user_id = ? AND client_id = ?
RETURNING id, user_id, client_id, scopes, granted_at
`

type UpdateConsentScopesParams struct {
	Scopes    string `json:"scopes"`
	GrantedAt int64  `json:"granted_at"`
	UserID    string `json:"user_id"`
	ClientID  string `json:"client_id"`
}

func (q *Queries) UpdateConsentScopes(ctx context.Context, arg UpdateConsentScopesParams) (OauthConsent, error) {
	row := q.db.QueryRowContext(ctx, updateConsentScopes,
		arg.Scopes,
		arg.GrantedAt,
		arg.UserID,
		arg.ClientID,
	)
	var i OauthConsent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClientID,
		&i.Scopes,
		&i.GrantedAt,
	)
	return i, err
}
