// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package userdb

import (
	"database/sql"
)

type Account struct {
	UserID             string         `json:"user_id"`
	Email              string         `json:"email"`
	PasswordHash       sql.NullString `json:"password_hash"`
	GoogleSub          sql.NullString `json:"google_sub"`
	CreatedAt          int64          `json:"created_at"`
	SubscriptionStatus sql.NullString `json:"subscription_status"`
	SubscriptionID     sql.NullString `json:"subscription_id"`
	DbSizeBytes        sql.NullInt64  `json:"db_size_bytes"`
	LastLogin          sql.NullInt64  `json:"last_login"`
}

type ApiKey struct {
	KeyID     string         `json:"key_id"`
	KeyHash   string         `json:"key_hash"`
	Scope     sql.NullString `json:"scope"`
	CreatedAt int64          `json:"created_at"`
	LastUsed  sql.NullInt64  `json:"last_used"`
}

type FtsNote struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

type Note struct {
	ID        string        `json:"id"`
	Title     string        `json:"title"`
	Content   string        `json:"content"`
	IsPublic  sql.NullInt64 `json:"is_public"`
	CreatedAt int64         `json:"created_at"`
	UpdatedAt int64         `json:"updated_at"`
}
