// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package userdb

import (
	"context"
	"database/sql"
)

type Querier interface {
	CountAPIKeys(ctx context.Context) (int64, error)
	CountNotes(ctx context.Context) (int64, error)
	CountPublicNotes(ctx context.Context) (int64, error)
	// FTS5 search operations
	// Note: FTS5 queries are handled separately in Go code due to sqlc limitations with virtual tables
	// The fts_notes table is a virtual table that sqlc cannot fully parse
	// API Key operations
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) error
	// User database queries (per-user encrypted database)
	// Account operations
	CreateAccount(ctx context.Context, arg CreateAccountParams) error
	// Notes CRUD operations
	CreateNote(ctx context.Context, arg CreateNoteParams) error
	DeleteAPIKey(ctx context.Context, id string) error
	DeleteAccount(ctx context.Context, userID string) error
	DeleteNote(ctx context.Context, id string) error
	GetAPIKeyByHash(ctx context.Context, tokenHash string) (ApiKey, error)
	GetAPIKeyByID(ctx context.Context, id string) (ApiKey, error)
	GetAccount(ctx context.Context, userID string) (Account, error)
	GetAccountByEmail(ctx context.Context, email string) (Account, error)
	GetAccountByStripeCustomerID(ctx context.Context, stripeCustomerID sql.NullString) (Account, error)
	GetNote(ctx context.Context, id string) (Note, error)
	// Storage size tracking
	GetTotalNotesSize(ctx context.Context) (interface{}, error)
	ListAPIKeys(ctx context.Context) ([]ListAPIKeysRow, error)
	ListNotes(ctx context.Context, arg ListNotesParams) ([]Note, error)
	ListPublicNotes(ctx context.Context, arg ListPublicNotesParams) ([]Note, error)
	NoteExists(ctx context.Context, id string) (int64, error)
	UpdateAPIKeyLastUsed(ctx context.Context, arg UpdateAPIKeyLastUsedParams) error
	UpdateAccountDBSize(ctx context.Context, arg UpdateAccountDBSizeParams) error
	UpdateAccountEmail(ctx context.Context, arg UpdateAccountEmailParams) error
	UpdateAccountGoogleSub(ctx context.Context, arg UpdateAccountGoogleSubParams) error
	UpdateAccountLastLogin(ctx context.Context, arg UpdateAccountLastLoginParams) error
	UpdateAccountPasswordHash(ctx context.Context, arg UpdateAccountPasswordHashParams) error
	UpdateAccountStripeCustomerID(ctx context.Context, arg UpdateAccountStripeCustomerIDParams) error
	UpdateAccountSubscription(ctx context.Context, arg UpdateAccountSubscriptionParams) error
	UpdateAccountSubscriptionFull(ctx context.Context, arg UpdateAccountSubscriptionFullParams) error
	UpdateNote(ctx context.Context, arg UpdateNoteParams) error
	UpdateNoteContent(ctx context.Context, arg UpdateNoteContentParams) error
	UpdateNotePublic(ctx context.Context, arg UpdateNotePublicParams) error
	UpdateNoteTitle(ctx context.Context, arg UpdateNoteTitleParams) error
}

var _ Querier = (*Queries)(nil)
