// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: user_queries.sql

package userdb

import (
	"context"
	"database/sql"
)

const countAPIKeys = `-- name: CountAPIKeys :one
SELECT COUNT(*) FROM api_keys
`

func (q *Queries) CountAPIKeys(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAPIKeys)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countNotes = `-- name: CountNotes :one
SELECT COUNT(*) FROM notes
`

func (q *Queries) CountNotes(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countNotes)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPublicNotes = `-- name: CountPublicNotes :one
SELECT COUNT(*) FROM notes WHERE is_public = 1
`

func (q *Queries) CountPublicNotes(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPublicNotes)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAPIKey = `-- name: CreateAPIKey :exec


INSERT INTO api_keys (id, name, token_hash, scope, expires_at, created_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateAPIKeyParams struct {
	ID        string         `json:"id"`
	Name      string         `json:"name"`
	TokenHash string         `json:"token_hash"`
	Scope     sql.NullString `json:"scope"`
	ExpiresAt int64          `json:"expires_at"`
	CreatedAt int64          `json:"created_at"`
}

// FTS5 search operations
// Note: FTS5 queries are handled separately in Go code due to sqlc limitations with virtual tables
// The fts_notes table is a virtual table that sqlc cannot fully parse
// API Key operations
func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) error {
	_, err := q.db.ExecContext(ctx, createAPIKey,
		arg.ID,
		arg.Name,
		arg.TokenHash,
		arg.Scope,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const createAccount = `-- name: CreateAccount :exec


INSERT INTO account (user_id, email, password_hash, google_sub, created_at, subscription_status, subscription_id, stripe_customer_id, db_size_bytes, last_login)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateAccountParams struct {
	UserID             string         `json:"user_id"`
	Email              string         `json:"email"`
	PasswordHash       sql.NullString `json:"password_hash"`
	GoogleSub          sql.NullString `json:"google_sub"`
	CreatedAt          int64          `json:"created_at"`
	SubscriptionStatus sql.NullString `json:"subscription_status"`
	SubscriptionID     sql.NullString `json:"subscription_id"`
	StripeCustomerID   sql.NullString `json:"stripe_customer_id"`
	DbSizeBytes        sql.NullInt64  `json:"db_size_bytes"`
	LastLogin          sql.NullInt64  `json:"last_login"`
}

// User database queries (per-user encrypted database)
// Account operations
func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) error {
	_, err := q.db.ExecContext(ctx, createAccount,
		arg.UserID,
		arg.Email,
		arg.PasswordHash,
		arg.GoogleSub,
		arg.CreatedAt,
		arg.SubscriptionStatus,
		arg.SubscriptionID,
		arg.StripeCustomerID,
		arg.DbSizeBytes,
		arg.LastLogin,
	)
	return err
}

const createNote = `-- name: CreateNote :exec

INSERT INTO notes (id, title, content, is_public, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateNoteParams struct {
	ID        string        `json:"id"`
	Title     string        `json:"title"`
	Content   string        `json:"content"`
	IsPublic  sql.NullInt64 `json:"is_public"`
	CreatedAt int64         `json:"created_at"`
	UpdatedAt int64         `json:"updated_at"`
}

// Notes CRUD operations
func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) error {
	_, err := q.db.ExecContext(ctx, createNote,
		arg.ID,
		arg.Title,
		arg.Content,
		arg.IsPublic,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteAPIKey = `-- name: DeleteAPIKey :exec
DELETE FROM api_keys WHERE id = ?
`

func (q *Queries) DeleteAPIKey(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteAPIKey, id)
	return err
}

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM account WHERE user_id = ?
`

func (q *Queries) DeleteAccount(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteAccount, userID)
	return err
}

const deleteNote = `-- name: DeleteNote :exec
DELETE FROM notes WHERE id = ?
`

func (q *Queries) DeleteNote(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteNote, id)
	return err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT id, name, token_hash, scope, expires_at, created_at, last_used_at
FROM api_keys
WHERE token_hash = ?
`

func (q *Queries) GetAPIKeyByHash(ctx context.Context, tokenHash string) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, getAPIKeyByHash, tokenHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TokenHash,
		&i.Scope,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getAPIKeyByID = `-- name: GetAPIKeyByID :one
SELECT id, name, token_hash, scope, expires_at, created_at, last_used_at
FROM api_keys
WHERE id = ?
`

func (q *Queries) GetAPIKeyByID(ctx context.Context, id string) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, getAPIKeyByID, id)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TokenHash,
		&i.Scope,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getAccount = `-- name: GetAccount :one
SELECT user_id, email, password_hash, google_sub, created_at, subscription_status, subscription_id, stripe_customer_id, db_size_bytes, last_login
FROM account
WHERE user_id = ?
`

func (q *Queries) GetAccount(ctx context.Context, userID string) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccount, userID)
	var i Account
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.PasswordHash,
		&i.GoogleSub,
		&i.CreatedAt,
		&i.SubscriptionStatus,
		&i.SubscriptionID,
		&i.StripeCustomerID,
		&i.DbSizeBytes,
		&i.LastLogin,
	)
	return i, err
}

const getAccountByEmail = `-- name: GetAccountByEmail :one
SELECT user_id, email, password_hash, google_sub, created_at, subscription_status, subscription_id, stripe_customer_id, db_size_bytes, last_login
FROM account
WHERE email = ?
`

func (q *Queries) GetAccountByEmail(ctx context.Context, email string) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccountByEmail, email)
	var i Account
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.PasswordHash,
		&i.GoogleSub,
		&i.CreatedAt,
		&i.SubscriptionStatus,
		&i.SubscriptionID,
		&i.StripeCustomerID,
		&i.DbSizeBytes,
		&i.LastLogin,
	)
	return i, err
}

const getAccountByStripeCustomerID = `-- name: GetAccountByStripeCustomerID :one
SELECT user_id, email, password_hash, google_sub, created_at, subscription_status, subscription_id, stripe_customer_id, db_size_bytes, last_login
FROM account
WHERE stripe_customer_id = ?
`

func (q *Queries) GetAccountByStripeCustomerID(ctx context.Context, stripeCustomerID sql.NullString) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccountByStripeCustomerID, stripeCustomerID)
	var i Account
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.PasswordHash,
		&i.GoogleSub,
		&i.CreatedAt,
		&i.SubscriptionStatus,
		&i.SubscriptionID,
		&i.StripeCustomerID,
		&i.DbSizeBytes,
		&i.LastLogin,
	)
	return i, err
}

const getNote = `-- name: GetNote :one
SELECT id, title, content, is_public, created_at, updated_at
FROM notes
WHERE id = ?
`

func (q *Queries) GetNote(ctx context.Context, id string) (Note, error) {
	row := q.db.QueryRowContext(ctx, getNote, id)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTotalNotesSize = `-- name: GetTotalNotesSize :one

SELECT COALESCE(SUM(length(title) + length(content)), 0) AS total_size FROM notes
`

// Storage size tracking
func (q *Queries) GetTotalNotesSize(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getTotalNotesSize)
	var total_size interface{}
	err := row.Scan(&total_size)
	return total_size, err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT id, name, scope, expires_at, created_at, last_used_at
FROM api_keys
ORDER BY created_at DESC
`

type ListAPIKeysRow struct {
	ID         string         `json:"id"`
	Name       string         `json:"name"`
	Scope      sql.NullString `json:"scope"`
	ExpiresAt  int64          `json:"expires_at"`
	CreatedAt  int64          `json:"created_at"`
	LastUsedAt sql.NullInt64  `json:"last_used_at"`
}

func (q *Queries) ListAPIKeys(ctx context.Context) ([]ListAPIKeysRow, error) {
	rows, err := q.db.QueryContext(ctx, listAPIKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAPIKeysRow{}
	for rows.Next() {
		var i ListAPIKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Scope,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotes = `-- name: ListNotes :many
SELECT id, title, content, is_public, created_at, updated_at
FROM notes
ORDER BY updated_at DESC
LIMIT ? OFFSET ?
`

type ListNotesParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListNotes(ctx context.Context, arg ListNotesParams) ([]Note, error) {
	rows, err := q.db.QueryContext(ctx, listNotes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.IsPublic,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicNotes = `-- name: ListPublicNotes :many
SELECT id, title, content, is_public, created_at, updated_at
FROM notes
WHERE is_public = 1
ORDER BY updated_at DESC
LIMIT ? OFFSET ?
`

type ListPublicNotesParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListPublicNotes(ctx context.Context, arg ListPublicNotesParams) ([]Note, error) {
	rows, err := q.db.QueryContext(ctx, listPublicNotes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.IsPublic,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const noteExists = `-- name: NoteExists :one
SELECT EXISTS(SELECT 1 FROM notes WHERE id = ?)
`

func (q *Queries) NoteExists(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRowContext(ctx, noteExists, id)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const updateAPIKeyLastUsed = `-- name: UpdateAPIKeyLastUsed :exec
UPDATE api_keys SET last_used_at = ? WHERE id = ?
`

type UpdateAPIKeyLastUsedParams struct {
	LastUsedAt sql.NullInt64 `json:"last_used_at"`
	ID         string        `json:"id"`
}

func (q *Queries) UpdateAPIKeyLastUsed(ctx context.Context, arg UpdateAPIKeyLastUsedParams) error {
	_, err := q.db.ExecContext(ctx, updateAPIKeyLastUsed, arg.LastUsedAt, arg.ID)
	return err
}

const updateAccountDBSize = `-- name: UpdateAccountDBSize :exec
UPDATE account SET db_size_bytes = ? WHERE user_id = ?
`

type UpdateAccountDBSizeParams struct {
	DbSizeBytes sql.NullInt64 `json:"db_size_bytes"`
	UserID      string        `json:"user_id"`
}

func (q *Queries) UpdateAccountDBSize(ctx context.Context, arg UpdateAccountDBSizeParams) error {
	_, err := q.db.ExecContext(ctx, updateAccountDBSize, arg.DbSizeBytes, arg.UserID)
	return err
}

const updateAccountEmail = `-- name: UpdateAccountEmail :exec
UPDATE account SET email = ? WHERE user_id = ?
`

type UpdateAccountEmailParams struct {
	Email  string `json:"email"`
	UserID string `json:"user_id"`
}

func (q *Queries) UpdateAccountEmail(ctx context.Context, arg UpdateAccountEmailParams) error {
	_, err := q.db.ExecContext(ctx, updateAccountEmail, arg.Email, arg.UserID)
	return err
}

const updateAccountGoogleSub = `-- name: UpdateAccountGoogleSub :exec
UPDATE account SET google_sub = ? WHERE user_id = ?
`

type UpdateAccountGoogleSubParams struct {
	GoogleSub sql.NullString `json:"google_sub"`
	UserID    string         `json:"user_id"`
}

func (q *Queries) UpdateAccountGoogleSub(ctx context.Context, arg UpdateAccountGoogleSubParams) error {
	_, err := q.db.ExecContext(ctx, updateAccountGoogleSub, arg.GoogleSub, arg.UserID)
	return err
}

const updateAccountLastLogin = `-- name: UpdateAccountLastLogin :exec
UPDATE account SET last_login = ? WHERE user_id = ?
`

type UpdateAccountLastLoginParams struct {
	LastLogin sql.NullInt64 `json:"last_login"`
	UserID    string        `json:"user_id"`
}

func (q *Queries) UpdateAccountLastLogin(ctx context.Context, arg UpdateAccountLastLoginParams) error {
	_, err := q.db.ExecContext(ctx, updateAccountLastLogin, arg.LastLogin, arg.UserID)
	return err
}

const updateAccountPasswordHash = `-- name: UpdateAccountPasswordHash :exec
UPDATE account SET password_hash = ? WHERE user_id = ?
`

type UpdateAccountPasswordHashParams struct {
	PasswordHash sql.NullString `json:"password_hash"`
	UserID       string         `json:"user_id"`
}

func (q *Queries) UpdateAccountPasswordHash(ctx context.Context, arg UpdateAccountPasswordHashParams) error {
	_, err := q.db.ExecContext(ctx, updateAccountPasswordHash, arg.PasswordHash, arg.UserID)
	return err
}

const updateAccountStripeCustomerID = `-- name: UpdateAccountStripeCustomerID :exec
UPDATE account SET stripe_customer_id = ? WHERE user_id = ?
`

type UpdateAccountStripeCustomerIDParams struct {
	StripeCustomerID sql.NullString `json:"stripe_customer_id"`
	UserID           string         `json:"user_id"`
}

func (q *Queries) UpdateAccountStripeCustomerID(ctx context.Context, arg UpdateAccountStripeCustomerIDParams) error {
	_, err := q.db.ExecContext(ctx, updateAccountStripeCustomerID, arg.StripeCustomerID, arg.UserID)
	return err
}

const updateAccountSubscription = `-- name: UpdateAccountSubscription :exec
UPDATE account SET subscription_status = ?, subscription_id = ? WHERE user_id = ?
`

type UpdateAccountSubscriptionParams struct {
	SubscriptionStatus sql.NullString `json:"subscription_status"`
	SubscriptionID     sql.NullString `json:"subscription_id"`
	UserID             string         `json:"user_id"`
}

func (q *Queries) UpdateAccountSubscription(ctx context.Context, arg UpdateAccountSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, updateAccountSubscription, arg.SubscriptionStatus, arg.SubscriptionID, arg.UserID)
	return err
}

const updateAccountSubscriptionFull = `-- name: UpdateAccountSubscriptionFull :exec
UPDATE account SET subscription_status = ?, subscription_id = ?, stripe_customer_id = ? WHERE user_id = ?
`

type UpdateAccountSubscriptionFullParams struct {
	SubscriptionStatus sql.NullString `json:"subscription_status"`
	SubscriptionID     sql.NullString `json:"subscription_id"`
	StripeCustomerID   sql.NullString `json:"stripe_customer_id"`
	UserID             string         `json:"user_id"`
}

func (q *Queries) UpdateAccountSubscriptionFull(ctx context.Context, arg UpdateAccountSubscriptionFullParams) error {
	_, err := q.db.ExecContext(ctx, updateAccountSubscriptionFull,
		arg.SubscriptionStatus,
		arg.SubscriptionID,
		arg.StripeCustomerID,
		arg.UserID,
	)
	return err
}

const updateNote = `-- name: UpdateNote :exec
UPDATE notes
SET title = ?, content = ?, is_public = ?, updated_at = ?
WHERE id = ?
`

type UpdateNoteParams struct {
	Title     string        `json:"title"`
	Content   string        `json:"content"`
	IsPublic  sql.NullInt64 `json:"is_public"`
	UpdatedAt int64         `json:"updated_at"`
	ID        string        `json:"id"`
}

func (q *Queries) UpdateNote(ctx context.Context, arg UpdateNoteParams) error {
	_, err := q.db.ExecContext(ctx, updateNote,
		arg.Title,
		arg.Content,
		arg.IsPublic,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateNoteContent = `-- name: UpdateNoteContent :exec
UPDATE notes SET content = ?, updated_at = ? WHERE id = ?
`

type UpdateNoteContentParams struct {
	Content   string `json:"content"`
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateNoteContent(ctx context.Context, arg UpdateNoteContentParams) error {
	_, err := q.db.ExecContext(ctx, updateNoteContent, arg.Content, arg.UpdatedAt, arg.ID)
	return err
}

const updateNotePublic = `-- name: UpdateNotePublic :exec
UPDATE notes SET is_public = ?, updated_at = ? WHERE id = ?
`

type UpdateNotePublicParams struct {
	IsPublic  sql.NullInt64 `json:"is_public"`
	UpdatedAt int64         `json:"updated_at"`
	ID        string        `json:"id"`
}

func (q *Queries) UpdateNotePublic(ctx context.Context, arg UpdateNotePublicParams) error {
	_, err := q.db.ExecContext(ctx, updateNotePublic, arg.IsPublic, arg.UpdatedAt, arg.ID)
	return err
}

const updateNoteTitle = `-- name: UpdateNoteTitle :exec
UPDATE notes SET title = ?, updated_at = ? WHERE id = ?
`

type UpdateNoteTitleParams struct {
	Title     string `json:"title"`
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateNoteTitle(ctx context.Context, arg UpdateNoteTitleParams) error {
	_, err := q.db.ExecContext(ctx, updateNoteTitle, arg.Title, arg.UpdatedAt, arg.ID)
	return err
}
