#!/usr/bin/env bash
# stripe-setup.sh - Milestone 6: Programmatically create Stripe products and prices
#
# Usage:
#   ./scripts/stripe-setup.sh [output-file]
#
# Arguments:
#   output-file  Optional. If provided, appends the exported price ID variables
#                to this file (e.g., secrets.sh).
#
# Required environment:
#   STRIPE_SECRET_KEY  Your Stripe secret key (sk_live_... or sk_test_...).
#                      Must be set before running this script.
#
# Output:
#   Prints the following to stdout (and optionally appends to output-file):
#     export STRIPE_PRICE_MONTHLY=price_xxx
#     export STRIPE_PRICE_ANNUAL=price_xxx
#
# Example:
#   STRIPE_SECRET_KEY="${STRIPE_SECRET_KEY}" ./scripts/stripe-setup.sh secrets.sh

set -euo pipefail

STRIPE_API_BASE="https://api.stripe.com/v1"

# --- Validate required environment ---

if [[ -z "${STRIPE_SECRET_KEY:-}" ]]; then
  echo "ERROR: STRIPE_SECRET_KEY is not set." >&2
  echo "Export it before running this script:" >&2
  echo "  export STRIPE_SECRET_KEY=<your-stripe-secret-key>" >&2
  exit 1
fi

# Verify jq is available
if ! command -v jq &>/dev/null; then
  echo "ERROR: jq is required but not found in PATH." >&2
  echo "Install it with: sudo apt-get install jq  (or brew install jq on macOS)" >&2
  exit 1
fi

# Verify curl is available
if ! command -v curl &>/dev/null; then
  echo "ERROR: curl is required but not found in PATH." >&2
  exit 1
fi

OUTPUT_FILE="${1:-}"

# --- Helper: make an authenticated Stripe API call ---
stripe_post() {
  local endpoint="$1"
  shift
  curl --silent --fail-with-body \
    -H "Authorization: Bearer ${STRIPE_SECRET_KEY}" \
    "${STRIPE_API_BASE}/${endpoint}" \
    "$@"
}

# --- Step 1: Create the "Common Ink Pro" product ---

echo "Creating 'Common Ink Pro' product..." >&2

PRODUCT_RESPONSE=$(stripe_post products \
  -d "name=Common Ink Pro" \
  -d "description=Full access to Common Ink note-taking and MCP features" \
  -d "metadata[created_by]=stripe-setup.sh")

PRODUCT_ID=$(echo "${PRODUCT_RESPONSE}" | jq -r '.id')

if [[ -z "${PRODUCT_ID}" || "${PRODUCT_ID}" == "null" ]]; then
  echo "ERROR: Failed to create product. Stripe response:" >&2
  echo "${PRODUCT_RESPONSE}" | jq . >&2
  exit 1
fi

echo "Created product: ${PRODUCT_ID}" >&2

# --- Step 2: Create the $2/month recurring price ---

echo "Creating \$2/month recurring price..." >&2

MONTHLY_RESPONSE=$(stripe_post prices \
  -d "product=${PRODUCT_ID}" \
  -d "unit_amount=200" \
  -d "currency=usd" \
  -d "recurring[interval]=month" \
  -d "nickname=Common Ink Pro Monthly" \
  -d "metadata[created_by]=stripe-setup.sh")

STRIPE_PRICE_MONTHLY=$(echo "${MONTHLY_RESPONSE}" | jq -r '.id')

if [[ -z "${STRIPE_PRICE_MONTHLY}" || "${STRIPE_PRICE_MONTHLY}" == "null" ]]; then
  echo "ERROR: Failed to create monthly price. Stripe response:" >&2
  echo "${MONTHLY_RESPONSE}" | jq . >&2
  exit 1
fi

echo "Created monthly price: ${STRIPE_PRICE_MONTHLY}" >&2

# --- Step 3: Create the $20/year recurring price ---

echo "Creating \$20/year recurring price..." >&2

ANNUAL_RESPONSE=$(stripe_post prices \
  -d "product=${PRODUCT_ID}" \
  -d "unit_amount=2000" \
  -d "currency=usd" \
  -d "recurring[interval]=year" \
  -d "nickname=Common Ink Pro Annual" \
  -d "metadata[created_by]=stripe-setup.sh")

STRIPE_PRICE_ANNUAL=$(echo "${ANNUAL_RESPONSE}" | jq -r '.id')

if [[ -z "${STRIPE_PRICE_ANNUAL}" || "${STRIPE_PRICE_ANNUAL}" == "null" ]]; then
  echo "ERROR: Failed to create annual price. Stripe response:" >&2
  echo "${ANNUAL_RESPONSE}" | jq . >&2
  exit 1
fi

echo "Created annual price: ${STRIPE_PRICE_ANNUAL}" >&2

# --- Step 4: Output the price ID exports ---

EXPORT_LINES="export STRIPE_PRICE_MONTHLY=${STRIPE_PRICE_MONTHLY}
export STRIPE_PRICE_ANNUAL=${STRIPE_PRICE_ANNUAL}"

echo ""
echo "${EXPORT_LINES}"

if [[ -n "${OUTPUT_FILE}" ]]; then
  echo "" >> "${OUTPUT_FILE}"
  echo "# Stripe price IDs (generated by stripe-setup.sh)" >> "${OUTPUT_FILE}"
  echo "${EXPORT_LINES}" >> "${OUTPUT_FILE}"
  echo "" >&2
  echo "Appended price IDs to: ${OUTPUT_FILE}" >&2
fi
